### ISSUE TITLE
NPM issue

### ISSUE THREAD

**Issue by npomfret** [bitfinexcom/bfx-api-node-util#12]
I'm having problems deploying an app to google cloud functions which contains Bitfinex NPM dependencies.  I just noticed this error in my build and think it's related (but don't know enough about NPM to track it down - sorry!).

`warning Pattern ["bfx-api-node-util@git+http://github.com/bitfinexcom/bfx-api-node-util.git#semver:^1.0.4"] is trying to unpack in the same destination "/Users/.../Library/Caches/Yarn/v4/npm-bfx-api-node-util-1.0.4-e1eeda2da78ac0bfa43d7d5d9598e1973e286b58/node_modules/bfx-api-node-util" as pattern ["bfx-api-node-util@git+http://github.com/bitfinexcom/bfx-api-node-util.git#semver:^1.0.2"]. This could result in non-deterministic behavior, skipping.
`

**Comment by f3rno** [comment]
@npomfret are you using `yarn` or `npm` to install the dependencies? It looks like the semver pattern is not being respected.

**Comment by npomfret** [comment]
@f3rno yarn

**Comment by f3rno** [comment]
@npomfret this will be fixed by this PR: https://github.com/bitfinexcom/bfx-api-node-util/pull/11

**Comment by npomfret** [comment]
thanks

**Comment by npomfret** [comment]
@f3rno thanks for the fix but there's still something wrong.  When I run my deployment I get an rpm error `Cannot read property '0' of undefined` (see below).  

The problem goes away if I `rm -rf node_modules/bfx-api-node*`... 

```
npm ERR! Cannot read property '0' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2019-10-15T13_11_07_382Z-debug.log

Error: An unexpected error has occurred.
$ cat /.npm/_logs/2019-10-15T13_11_07_382Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/.nvm/versions/node/v10.16.3/bin/node',
1 verbose cli   '/.nvm/versions/node/v10.16.3/bin/npm',
1 verbose cli   'outdated',
1 verbose cli   'firebase-functions',
1 verbose cli   '--json=true' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose npm-session 5f0550300d62e70c
5 verbose stack TypeError: Cannot read property '0' of undefined
5 verbose stack     at npa (/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:30:25)
5 verbose stack     at doesChildVersionMatch (/.nvm/versions/node/v10.16.3/lib/node_modules/npm/lib/install/deps.js:61:22)
5 verbose stack     at versionMatch (/.nvm/versions/node/v10.16.3/lib/node_modules/npm/lib/install/deps.js:747:12)
5 verbose stack     at Array.filter (<anonymous>)
5 verbose stack     at exports.findRequirement (/.nvm/versions/node/v10.16.3/lib/node_modules/npm/lib/install/deps.js:757:23)
5 verbose stack     at findChild (/.nvm/versions/node/v10.16.3/lib/node_modules/npm/lib/install/deps.js:122:17)
5 verbose stack     at computeMetadata (/.nvm/versions/node/v10.16.3/lib/node_modules/npm/lib/install/deps.js:132:9)
5 verbose stack     at tree.children.filter.forEach (/.nvm/versions/node/v10.16.3/lib/node_modules/npm/lib/install/deps.js:144:70)
5 verbose stack     at Array.forEach (<anonymous>)
5 verbose stack     at computeMetadata (/.nvm/versions/node/v10.16.3/lib/node_modules/npm/lib/install/deps.js:144:51)
5 verbose stack     at /.nvm/versions/node/v10.16.3/lib/node_modules/npm/lib/outdated.js:81:16
5 verbose stack     at thenHandleErrors (/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:247:5)
5 verbose stack     at f (/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/once/once.js:25:25)
5 verbose stack     at handleComplete (/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:22:28)
5 verbose stack     at f (/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/once/once.js:25:25)
5 verbose stack     at handleComplete (/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:22:28)
6 verbose cwd /projects/crypto-trader-prototype/firebase/functions
7 verbose Darwin 19.0.0
8 verbose argv "/.nvm/versions/node/v10.16.3/bin/node" "/.nvm/versions/node/v10.16.3/bin/npm" "outdated" "firebase-functions" "--json=true"
9 verbose node v10.16.3
10 verbose npm  v6.9.0
11 error Cannot read property '0' of undefined
12 verbose exit [ 1, true ]
```

```
$ yarn --version
1.19.1
$ npm --version
6.9.0
$ node --version
v10.16.3
```

**Comment by f3rno** [comment]
@npomfret I've seen this too, it occurs intermittently with different repos when versions are changed in deps, I'm not sure why.

The fix for me is:
```bash
rm -rf node_modules
rm package-lock.json
(note links if you have them)
npm i
(re-apply links if needed)
```

Can you confirm this works?

**Comment by npomfret** [comment]
I use yarn rather than npm, and I can confirm it's 100% reproducible. Deleting and reinstalling node_modules has no effect.  

I've narrowed it down to a problem in bfx-api-node-rest though.  The others seem to be ok.
